### ISSUE TITLE
Multivariate Output for bama

### ISSUE THREAD

**Issue by dbrennan44** [umich-cphds/hdbm#5]
Hello,
I hope this is an appropriate place to leave my question.

I'm hoping to use the methods available in bama to test a number of multivariate mediators on multiple outputs simultaneously. However, bama and associated text focus on a single output variable. How can bama be utilized to test multiple output variables from the same mediating/exposure variables?

**Comment by tzimiskes** [comment]
Hello!

You will have to run bama separately for each outcome variable

Alex
